// Code generated by packager ["-local" "defaultFoo" "-block" "Init"] -- DO NOT EDIT
//go:build !packager
// +build !packager

package example

// Next is package exported version of "func (*foo).Next() int" called on a package level value.
func Next() int {
	return defaultFoo.Next()
}

// Peek is package exported version of "func (foo).Peek() int" called on a package level value.
func Peek() int {
	return defaultFoo.Peek()
}

// Reset is package exported version of "func (*foo).Reset(n int)" called on a package level value.
func Reset(n int) {
	defaultFoo.Reset(n)
}
